### ISSUE TITLE
Mathjax 3 doesn't work with LaTeX macros

### ISSUE THREAD

**Issue by furnstahl** [furnstahl/Physics-8820#1]
Using in _config.yml:

```
sphinx:
  config:
    bibtex_reference_style: label
    bibtex_default_style: 'alpha'    
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    mathjax_config:
      TeX:
        Macros:
          "N": ["\\mathbb{N}"]
          "Z": ["\\mathbb{Z}"]
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat" : ["\\left[\\begin{array}"]
          "emat" : ["\\end{array}\\right]"]
          "thetavec": ["\\boldsymbol{\\theta}"]
          "Lra" : ["\\Longrightarrow"]

```
but the LaTeX macros don't work. They *do* work if we kick back to mathjax@2, so maybe it is a syntax problem?
